artifact_location: /Users/masterbee/Desktop/Upgrade Skills/Udemy - MLflow in Action
  - Master the art of MLOps using MLflow tool 2024-8/code/day-04-mlflow-ui-and-tracking-uri/mytracks/0
creation_time: 1757746799462
experiment_id: '0'
last_update_time: 1757746799462
lifecycle_stage: active
name: Default
