artifact_location: /Users/masterbee/Desktop/Upgrade Skills/Udemy - MLflow in Action
  - Master the art of MLOps using MLflow tool 2024-8/code/day-04-mlflow-ui-and-tracking-uri/mytracks/830426353753042762
creation_time: 1757746799468
experiment_id: '830426353753042762'
last_update_time: 1757746799468
lifecycle_stage: active
name: ElasticNet-Wine-Quality-1
